version: '3.8'
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: space_linkd_auth_db
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin","ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
  auth-service:
    build: 
      context: ../..
      dockerfile: apps/auth-service/Dockerfile
    environment:
      DBMYSQL_AUTH_HOST_HOST: mysql
      MYSQL_AUTH_PORT: 3306
      MYSQL_AUTH_USER: root
      MYSQL_AUTH_PASSWORD: root
      MYSQL_AUTH_DATABASE: space_linkd_auth_db
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy


