version: '3.8'
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: space_linkd_property_db

    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin","ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
  property-service:
    build: 
      context: ../..
      dockerfile: apps/property-service/Dockerfile
    environment:
      MYSQL_PROPERTY_HOST: mysql
      MYSQL_PROPERTY_PORT: 3306
      MYSQL_PROPERTY_USER: root
      MYSQL_PROPERTY_PASSWORD: root
      MYSQL_PROPERTY_DATABASE: space_linkd_property_db
    ports:
      - "3001:3001"
    depends_on:
      mysql:
        condition: service_healthy


